// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_PIDTUNNER
void ui_PIDTUNNER_screen_init(void);
lv_obj_t * ui_PIDTUNNER;
lv_obj_t * ui_PAD;
lv_obj_t * ui_TEXT;
lv_obj_t * ui_PADIN;
lv_obj_t * ui_TEXTIN;
void ui_event_DROPDOWN(lv_event_t * e);
lv_obj_t * ui_DROPDOWN;
void ui_event_DROPDOWN1(lv_event_t * e);
lv_obj_t * ui_DROPDOWN1;
void ui_event_DROPDOWN2(lv_event_t * e);
lv_obj_t * ui_DROPDOWN2;
lv_obj_t * ui_SLIDERPAD;
void ui_event_SLIDER(lv_event_t * e);
lv_obj_t * ui_SLIDER;
lv_obj_t * ui_SLIDERT;
lv_obj_t * ui_SLIDERPAD1;
void ui_event_SLIDER1(lv_event_t * e);
lv_obj_t * ui_SLIDER1;
lv_obj_t * ui_SLIDERT1;
lv_obj_t * ui_SLIDERPAD2;
void ui_event_SLIDER2(lv_event_t * e);
lv_obj_t * ui_SLIDER2;
lv_obj_t * ui_SLIDERT2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_PDATAT;
lv_obj_t * ui_IDATAT;
lv_obj_t * ui_DDATAT;
void ui_event_BTNSEND(lv_event_t * e);
lv_obj_t * ui_BTNSEND;
lv_obj_t * ui_BTNT;
lv_obj_t * ui_KEEPPAD;
void ui_event_KEEPSWITCH(lv_event_t * e);
lv_obj_t * ui_KEEPSWITCH;
lv_obj_t * ui_KEEPT;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_DROPDOWN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        P_RATE_CHANGE(e);
    }
}
void ui_event_DROPDOWN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        I_RATE_CHANGE(e);
    }
}
void ui_event_DROPDOWN2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        D_RATE_CHANGE(e);
    }
}
void ui_event_SLIDER(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        CHANGE_P(e);
    }
}
void ui_event_SLIDER1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        CHANGE_I(e);
    }
}
void ui_event_SLIDER2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        CHANGE_D(e);
    }
}
void ui_event_BTNSEND(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SEND_ONCE(e);
    }
}
void ui_event_KEEPSWITCH(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        KEEP_ON_SEND(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_PIDTUNNER_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_PIDTUNNER);
}
