// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"


#include "ui_helpers.h"
#include "ui_events.h"
#include "stdint.h"
#include "stdio.h"


typedef struct {

    uint8_t send_flag ;

    uint16_t P_SET ;
    uint16_t I_SET ;
    uint16_t D_SET ;

    float p_rate ;
    float i_rate ;
    float d_rate ;

    float p_value ;
    float i_value ;
    float d_value ;

} PIDTUNNER_Elements;





// SCREEN: ui_PIDTUNNER
void ui_PIDTUNNER_screen_init(void);
extern lv_obj_t * ui_PIDTUNNER;
extern lv_obj_t * ui_PAD;
extern lv_obj_t * ui_TEXT;
extern lv_obj_t * ui_PADIN;
extern lv_obj_t * ui_TEXTIN;
void ui_event_DROPDOWN(lv_event_t * e);
extern lv_obj_t * ui_DROPDOWN;
void ui_event_DROPDOWN1(lv_event_t * e);
extern lv_obj_t * ui_DROPDOWN1;
void ui_event_DROPDOWN2(lv_event_t * e);
extern lv_obj_t * ui_DROPDOWN2;
extern lv_obj_t * ui_SLIDERPAD;
void ui_event_SLIDER(lv_event_t * e);
extern lv_obj_t * ui_SLIDER;
extern lv_obj_t * ui_SLIDERT;
extern lv_obj_t * ui_SLIDERPAD1;
void ui_event_SLIDER1(lv_event_t * e);
extern lv_obj_t * ui_SLIDER1;
extern lv_obj_t * ui_SLIDERT1;
extern lv_obj_t * ui_SLIDERPAD2;
void ui_event_SLIDER2(lv_event_t * e);
extern lv_obj_t * ui_SLIDER2;
extern lv_obj_t * ui_SLIDERT2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_PDATAT;
extern lv_obj_t * ui_IDATAT;
extern lv_obj_t * ui_DDATAT;
void ui_event_BTNSEND(lv_event_t * e);
extern lv_obj_t * ui_BTNSEND;
extern lv_obj_t * ui_BTNT;
extern lv_obj_t * ui_KEEPPAD;
void ui_event_KEEPSWITCH(lv_event_t * e);
extern lv_obj_t * ui_KEEPSWITCH;
extern lv_obj_t * ui_KEEPT;
extern lv_obj_t * ui____initial_actions0;






extern PIDTUNNER_Elements PID_Data;


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
