// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void P_RATE_CHANGE(lv_event_t * e);
void I_RATE_CHANGE(lv_event_t * e);
void D_RATE_CHANGE(lv_event_t * e);
void CHANGE_P(lv_event_t * e);
void CHANGE_I(lv_event_t * e);
void CHANGE_D(lv_event_t * e);
void SEND_ONCE(lv_event_t * e);
void KEEP_ON_SEND(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
