// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

PIDTUNNER_Elements PID_Data = {

	.send_flag = 0,

	.P_SET = 0,
	.I_SET = 0,
	.D_SET = 0,

	.p_rate = 1.0f,
	.i_rate = 1.0f,
	.d_rate = 1.0f,

	.p_value = 0.0f,
	.i_value = 0.0f,
	.d_value = 0.0f,
};


char str[10];

void P_RATE_CHANGE(lv_event_t * e)
{
	// Your code here
	uint16_t selected = lv_dropdown_get_selected(ui_DROPDOWN);
	if(selected==0){PID_Data.p_rate=1.0f;}
	else if(selected==1){PID_Data.p_rate=10.0f;}
	else if(selected==2){PID_Data.p_rate=0.1f;}
	PID_Data.p_value = PID_Data.P_SET*PID_Data.p_rate;
	sprintf(str, "P: %.2f", PID_Data.p_value);
	lv_label_set_text(ui_PDATAT, str);
}

void I_RATE_CHANGE(lv_event_t * e)
{
	// Your code here
	uint16_t selected = lv_dropdown_get_selected(ui_DROPDOWN1);
	if (selected == 0) { PID_Data.i_rate = 1.0f; }
	else if (selected == 1) { PID_Data.i_rate = 10.0f; }
	else if (selected == 2) { PID_Data.i_rate = 0.1f; }
	PID_Data.i_value = PID_Data.I_SET*PID_Data.i_rate;
	sprintf(str, "I: %.2f", PID_Data.i_value);
	lv_label_set_text(ui_IDATAT, str);
}

void D_RATE_CHANGE(lv_event_t * e)
{
	// Your code here
	uint16_t selected = lv_dropdown_get_selected(ui_DROPDOWN2);
	if (selected == 0) { PID_Data.d_rate = 1.0f; }
	else if (selected == 1) { PID_Data.d_rate = 10.0f; }
	else if (selected == 2) { PID_Data.d_rate = 0.1f; }
	PID_Data.d_value = PID_Data.D_SET*PID_Data.d_rate;
	sprintf(str, "D: %.2f", PID_Data.d_value);
	lv_label_set_text(ui_DDATAT, str);
}


void CHANGE_P(lv_event_t * e)
{
	// Your code here
	PID_Data.P_SET = lv_slider_get_value(ui_SLIDER);
	PID_Data.p_value = PID_Data.P_SET*PID_Data.p_rate;
	sprintf(str, "P: %.2f", PID_Data.p_value);
	lv_label_set_text(ui_PDATAT, str);
}

void CHANGE_I(lv_event_t * e)
{
	// Your code here
	PID_Data.I_SET = lv_slider_get_value(ui_SLIDER1);
	PID_Data.i_value = PID_Data.I_SET*PID_Data.i_rate;
	sprintf(str, "I: %.2f", PID_Data.i_value);
	lv_label_set_text(ui_IDATAT, str);
}

void CHANGE_D(lv_event_t * e)
{
	// Your code here
	PID_Data.D_SET = lv_slider_get_value(ui_SLIDER2);
	PID_Data.d_value = PID_Data.D_SET*PID_Data.d_rate;
	sprintf(str, "D: %.2f", PID_Data.d_value);
	lv_label_set_text(ui_DDATAT, str);
}


void SEND_ONCE(lv_event_t * e)
{
	// Your code here
	PID_Data.send_flag = 1;
}


void KEEP_ON_SEND(lv_event_t * e)
{
	// Your code here
	if(PID_Data.send_flag==2){PID_Data.send_flag=0;}
	else if(PID_Data.send_flag==0){PID_Data.send_flag=2;}
}

