// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_PIDTUNNER_screen_init(void)
{
    ui_PIDTUNNER = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PIDTUNNER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PIDTUNNER, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PIDTUNNER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PAD = lv_obj_create(ui_PIDTUNNER);
    lv_obj_set_width(ui_PAD, 166);
    lv_obj_set_height(ui_PAD, 40);
    lv_obj_set_x(ui_PAD, 36);
    lv_obj_set_y(ui_PAD, 3);
    lv_obj_clear_flag(ui_PAD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PAD, lv_color_hex(0x0B0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PAD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEXT = lv_label_create(ui_PAD);
    lv_obj_set_width(ui_TEXT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEXT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEXT, -40);
    lv_obj_set_y(ui_TEXT, 0);
    lv_obj_set_align(ui_TEXT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEXT, "PID");

    ui_PADIN = lv_obj_create(ui_PAD);
    lv_obj_set_width(ui_PADIN, 78);
    lv_obj_set_height(ui_PADIN, 28);
    lv_obj_set_x(ui_PADIN, 15);
    lv_obj_set_y(ui_PADIN, 0);
    lv_obj_set_align(ui_PADIN, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PADIN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PADIN, lv_color_hex(0xFE9A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PADIN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEXTIN = lv_label_create(ui_PADIN);
    lv_obj_set_width(ui_TEXTIN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEXTIN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TEXTIN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEXTIN, "TUNNER");
    lv_obj_set_style_text_color(ui_TEXTIN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TEXTIN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DROPDOWN = lv_dropdown_create(ui_PIDTUNNER);
    lv_dropdown_set_options(ui_DROPDOWN, "P:  1 X\nP: 10X\nP:0.1X");
    lv_obj_set_width(ui_DROPDOWN, 76);
    lv_obj_set_height(ui_DROPDOWN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DROPDOWN, -81);
    lv_obj_set_y(ui_DROPDOWN, -77);
    lv_obj_set_align(ui_DROPDOWN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DROPDOWN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_DROPDOWN, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DROPDOWN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_DROPDOWN, lv_color_hex(0xFE9A00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DROPDOWN, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DROPDOWN), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DROPDOWN), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DROPDOWN), lv_color_hex(0xFE9A00),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DROPDOWN), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DROPDOWN), lv_color_hex(0xFE9A00),
                              LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DROPDOWN), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);

    ui_DROPDOWN1 = lv_dropdown_create(ui_PIDTUNNER);
    lv_dropdown_set_options(ui_DROPDOWN1, "I:  1 X\nI: 10X\nI:0.1X");
    lv_obj_set_width(ui_DROPDOWN1, 76);
    lv_obj_set_height(ui_DROPDOWN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DROPDOWN1, -2);
    lv_obj_set_y(ui_DROPDOWN1, -77);
    lv_obj_set_align(ui_DROPDOWN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DROPDOWN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_DROPDOWN1, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DROPDOWN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_DROPDOWN1, lv_color_hex(0xFE9A00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DROPDOWN1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DROPDOWN1), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DROPDOWN1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DROPDOWN1), lv_color_hex(0xFE9A00),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DROPDOWN1), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DROPDOWN1), lv_color_hex(0xFE9A00),
                              LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DROPDOWN1), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);

    ui_DROPDOWN2 = lv_dropdown_create(ui_PIDTUNNER);
    lv_dropdown_set_options(ui_DROPDOWN2, "D:  1 X\nD: 10X\nD:0.1X");
    lv_obj_set_width(ui_DROPDOWN2, 77);
    lv_obj_set_height(ui_DROPDOWN2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DROPDOWN2, 78);
    lv_obj_set_y(ui_DROPDOWN2, -77);
    lv_obj_set_align(ui_DROPDOWN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DROPDOWN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_DROPDOWN2, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DROPDOWN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_DROPDOWN2, lv_color_hex(0xFE9A00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DROPDOWN2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DROPDOWN2), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DROPDOWN2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DROPDOWN2), lv_color_hex(0xFE9A00),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DROPDOWN2), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DROPDOWN2), lv_color_hex(0xFE9A00),
                              LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DROPDOWN2), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);

    ui_SLIDERPAD = lv_obj_create(ui_PIDTUNNER);
    lv_obj_set_width(ui_SLIDERPAD, 230);
    lv_obj_set_height(ui_SLIDERPAD, 41);
    lv_obj_set_x(ui_SLIDERPAD, -1);
    lv_obj_set_y(ui_SLIDERPAD, -37);
    lv_obj_set_align(ui_SLIDERPAD, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SLIDERPAD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SLIDERPAD, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDERPAD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLIDER = lv_slider_create(ui_SLIDERPAD);
    lv_slider_set_value(ui_SLIDER, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SLIDER) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SLIDER, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SLIDER, 175);
    lv_obj_set_height(ui_SLIDER, 17);
    lv_obj_set_x(ui_SLIDER, 8);
    lv_obj_set_y(ui_SLIDER, 0);
    lv_obj_set_align(ui_SLIDER, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SLIDER, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SLIDER, lv_color_hex(0xFE9A00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDER, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SLIDER, lv_color_hex(0xFE9A00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDER, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SLIDERT = lv_label_create(ui_SLIDERPAD);
    lv_obj_set_width(ui_SLIDERT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLIDERT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SLIDERT, -104);
    lv_obj_set_y(ui_SLIDERT, 1);
    lv_obj_set_align(ui_SLIDERT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLIDERT, "P:");

    ui_SLIDERPAD1 = lv_obj_create(ui_PIDTUNNER);
    lv_obj_set_width(ui_SLIDERPAD1, 230);
    lv_obj_set_height(ui_SLIDERPAD1, 39);
    lv_obj_set_x(ui_SLIDERPAD1, -1);
    lv_obj_set_y(ui_SLIDERPAD1, 3);
    lv_obj_set_align(ui_SLIDERPAD1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SLIDERPAD1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SLIDERPAD1, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDERPAD1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLIDER1 = lv_slider_create(ui_SLIDERPAD1);
    lv_slider_set_value(ui_SLIDER1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SLIDER1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SLIDER1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SLIDER1, 175);
    lv_obj_set_height(ui_SLIDER1, 17);
    lv_obj_set_x(ui_SLIDER1, 8);
    lv_obj_set_y(ui_SLIDER1, 0);
    lv_obj_set_align(ui_SLIDER1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SLIDER1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDER1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SLIDER1, lv_color_hex(0xFE9A00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDER1, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SLIDER1, lv_color_hex(0xFE9A00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDER1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SLIDERT1 = lv_label_create(ui_SLIDERPAD1);
    lv_obj_set_width(ui_SLIDERT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLIDERT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SLIDERT1, -104);
    lv_obj_set_y(ui_SLIDERT1, 1);
    lv_obj_set_align(ui_SLIDERT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLIDERT1, "I:");

    ui_SLIDERPAD2 = lv_obj_create(ui_PIDTUNNER);
    lv_obj_set_width(ui_SLIDERPAD2, 230);
    lv_obj_set_height(ui_SLIDERPAD2, 38);
    lv_obj_set_x(ui_SLIDERPAD2, -1);
    lv_obj_set_y(ui_SLIDERPAD2, 42);
    lv_obj_set_align(ui_SLIDERPAD2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SLIDERPAD2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SLIDERPAD2, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDERPAD2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLIDER2 = lv_slider_create(ui_SLIDERPAD2);
    lv_slider_set_value(ui_SLIDER2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SLIDER2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SLIDER2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SLIDER2, 175);
    lv_obj_set_height(ui_SLIDER2, 17);
    lv_obj_set_x(ui_SLIDER2, 8);
    lv_obj_set_y(ui_SLIDER2, 0);
    lv_obj_set_align(ui_SLIDER2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SLIDER2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDER2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SLIDER2, lv_color_hex(0xFE9A00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDER2, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SLIDER2, lv_color_hex(0xFE9A00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SLIDER2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SLIDERT2 = lv_label_create(ui_SLIDERPAD2);
    lv_obj_set_width(ui_SLIDERT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLIDERT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SLIDERT2, -104);
    lv_obj_set_y(ui_SLIDERT2, 1);
    lv_obj_set_align(ui_SLIDERT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLIDERT2, "D:");

    ui_Panel1 = lv_obj_create(ui_PIDTUNNER);
    lv_obj_set_width(ui_Panel1, 141);
    lv_obj_set_height(ui_Panel1, 67);
    lv_obj_set_x(ui_Panel1, -37);
    lv_obj_set_y(ui_Panel1, 97);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PDATAT = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_PDATAT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PDATAT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PDATAT, -9);
    lv_obj_set_y(ui_PDATAT, -6);
    lv_label_set_text(ui_PDATAT, "P: 0.00");

    ui_IDATAT = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_IDATAT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDATAT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDATAT, -7);
    lv_obj_set_y(ui_IDATAT, 10);
    lv_label_set_text(ui_IDATAT, "I : 0.00");

    ui_DDATAT = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_DDATAT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DDATAT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DDATAT, -11);
    lv_obj_set_y(ui_DDATAT, 27);
    lv_label_set_text(ui_DDATAT, "D: 0.00");

    ui_BTNSEND = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_BTNSEND, 46);
    lv_obj_set_height(ui_BTNSEND, 42);
    lv_obj_set_x(ui_BTNSEND, 38);
    lv_obj_set_y(ui_BTNSEND, 1);
    lv_obj_set_align(ui_BTNSEND, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BTNSEND, lv_color_hex(0xFE9A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNSEND, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNT = lv_label_create(ui_BTNSEND);
    lv_obj_set_width(ui_BTNT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTNT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTNT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BTNT, "SEND");
    lv_obj_set_style_text_color(ui_BTNT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTNT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KEEPPAD = lv_obj_create(ui_PIDTUNNER);
    lv_obj_set_width(ui_KEEPPAD, 69);
    lv_obj_set_height(ui_KEEPPAD, 66);
    lv_obj_set_x(ui_KEEPPAD, 73);
    lv_obj_set_y(ui_KEEPPAD, 97);
    lv_obj_set_align(ui_KEEPPAD, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_KEEPPAD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_KEEPPAD, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KEEPPAD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KEEPSWITCH = lv_switch_create(ui_KEEPPAD);
    lv_obj_set_width(ui_KEEPSWITCH, 50);
    lv_obj_set_height(ui_KEEPSWITCH, 25);
    lv_obj_set_x(ui_KEEPSWITCH, 0);
    lv_obj_set_y(ui_KEEPSWITCH, -10);
    lv_obj_set_align(ui_KEEPSWITCH, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_KEEPSWITCH, lv_color_hex(0xFE9A00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_KEEPSWITCH, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_KEEPSWITCH, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_KEEPSWITCH, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_KEEPT = lv_label_create(ui_KEEPPAD);
    lv_obj_set_width(ui_KEEPT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KEEPT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KEEPT, -1);
    lv_obj_set_y(ui_KEEPT, 16);
    lv_obj_set_align(ui_KEEPT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KEEPT, "KEEP");

    lv_obj_add_event_cb(ui_DROPDOWN, ui_event_DROPDOWN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DROPDOWN1, ui_event_DROPDOWN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DROPDOWN2, ui_event_DROPDOWN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SLIDER, ui_event_SLIDER, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SLIDER1, ui_event_SLIDER1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SLIDER2, ui_event_SLIDER2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNSEND, ui_event_BTNSEND, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KEEPSWITCH, ui_event_KEEPSWITCH, LV_EVENT_ALL, NULL);

}
